/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/tmp/gen_env/../vehicle_captain_its_asn1_specifications/etsi/cdd_ts102894_2/ITS-Container.asn"
 * 	`asn1c -D /tmp/gen_env/vcits/srem -R -no-gen-example -fcompound-names -fno-include-deps -pdu=SREM`
 */

#ifndef	_SemiAxisLength_H_
#define	_SemiAxisLength_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SemiAxisLength {
	SemiAxisLength_oneCentimeter	= 1,
	SemiAxisLength_outOfRange	= 4094,
	SemiAxisLength_unavailable	= 4095
} e_SemiAxisLength;

/* SemiAxisLength */
typedef long	 SemiAxisLength_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SemiAxisLength_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SemiAxisLength;
asn_struct_free_f SemiAxisLength_free;
asn_struct_print_f SemiAxisLength_print;
asn_constr_check_f SemiAxisLength_constraint;
ber_type_decoder_f SemiAxisLength_decode_ber;
der_type_encoder_f SemiAxisLength_encode_der;
xer_type_decoder_f SemiAxisLength_decode_xer;
xer_type_encoder_f SemiAxisLength_encode_xer;
oer_type_decoder_f SemiAxisLength_decode_oer;
oer_type_encoder_f SemiAxisLength_encode_oer;
per_type_decoder_f SemiAxisLength_decode_uper;
per_type_encoder_f SemiAxisLength_encode_uper;
per_type_decoder_f SemiAxisLength_decode_aper;
per_type_encoder_f SemiAxisLength_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SemiAxisLength_H_ */
#include <asn_internal.h>
