/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "SREM-PDU-Descriptions"
 * 	found in "/tmp/gen_env/../vehicle_captain_its_asn1_specifications/etsi/is_ts103301/SREM-PDU-Descriptions.asn"
 * 	`asn1c -D /tmp/gen_env/vcits/srem -R -no-gen-example -fcompound-names -fno-include-deps -pdu=SREM`
 */

#ifndef	_SREM_H_
#define	_SREM_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ItsPduHeader.h"
#include "SignalRequestMessage.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* SREM */
typedef struct SREM {
	ItsPduHeader_t	 header;
	SignalRequestMessage_t	 srm;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} SREM_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_SREM;

#ifdef __cplusplus
}
#endif

#endif	/* _SREM_H_ */
#include <asn_internal.h>
