/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "GDD"
 * 	found in "/tmp/gen_env/../vehicle_captain_its_asn1_specifications/etsi/is_ts103301/iso-patched/ISO14823-missing.asn"
 * 	`asn1c -D /tmp/gen_env/vcits/ivim -R -no-gen-example -fcompound-names -fno-include-deps -pdu=IVIM`
 */

#ifndef	_DestinationPlace_H_
#define	_DestinationPlace_H_


#include <asn_application.h>

/* Including external dependencies */
#include "DestinationType.h"
#include <OCTET_STRING.h>
#include <NativeInteger.h>
#include <UTF8String.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct GddStructure;

/* DestinationPlace */
typedef struct DestinationPlace {
	DestinationType_t	 destType;
	struct GddStructure	*destRSCode;	/* OPTIONAL */
	OCTET_STRING_t	*destBlob;	/* OPTIONAL */
	long	*placeNameIdentification;	/* OPTIONAL */
	UTF8String_t	*placeNameText;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} DestinationPlace_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_DestinationPlace;
extern asn_SEQUENCE_specifics_t asn_SPC_DestinationPlace_specs_1;
extern asn_TYPE_member_t asn_MBR_DestinationPlace_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _DestinationPlace_H_ */
#include <asn_internal.h>
