/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "/tmp/gen_env/build/asn1/ISO19321IVIv2.asn"
 * 	`asn1c -D /tmp/gen_env/vcits/ivim -R -no-gen-example -fcompound-names -fno-include-deps -pdu=IVIM`
 */

#ifndef	_GeographicLocationContainer_H_
#define	_GeographicLocationContainer_H_


#include <asn_application.h>

/* Including external dependencies */
#include "ReferencePosition.h"
#include "TimestampIts.h"
#include "GlcParts.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct Heading;
struct Speed;

/* GeographicLocationContainer */
typedef struct GeographicLocationContainer {
	ReferencePosition_t	 referencePosition;
	TimestampIts_t	*referencePositionTime;	/* OPTIONAL */
	struct Heading	*referencePositionHeading;	/* OPTIONAL */
	struct Speed	*referencePositionSpeed;	/* OPTIONAL */
	GlcParts_t	 parts;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} GeographicLocationContainer_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_GeographicLocationContainer;
extern asn_SEQUENCE_specifics_t asn_SPC_GeographicLocationContainer_specs_1;
extern asn_TYPE_member_t asn_MBR_GeographicLocationContainer_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _GeographicLocationContainer_H_ */
#include <asn_internal.h>
