/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "ITS-Container"
 * 	found in "/tmp/gen_env/../vehicle_captain_its_asn1_specifications/etsi/cdd_ts102894_2/ITS-Container.asn"
 * 	`asn1c -D /tmp/gen_env/vcits/ivim -R -no-gen-example -fcompound-names -fno-include-deps -pdu=IVIM`
 */

#ifndef	_ITS_Container_StationType_H_
#define	_ITS_Container_StationType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum ITS_Container_StationType {
	ITS_Container_StationType_unknown	= 0,
	ITS_Container_StationType_pedestrian	= 1,
	ITS_Container_StationType_cyclist	= 2,
	ITS_Container_StationType_moped	= 3,
	ITS_Container_StationType_motorcycle	= 4,
	ITS_Container_StationType_passengerCar	= 5,
	ITS_Container_StationType_bus	= 6,
	ITS_Container_StationType_lightTruck	= 7,
	ITS_Container_StationType_heavyTruck	= 8,
	ITS_Container_StationType_trailer	= 9,
	ITS_Container_StationType_specialVehicles	= 10,
	ITS_Container_StationType_tram	= 11,
	ITS_Container_StationType_roadSideUnit	= 15
} e_ITS_Container_StationType;

/* ITS-Container_StationType */
typedef long	 ITS_Container_StationType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ITS_Container_StationType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ITS_Container_StationType;
asn_struct_free_f ITS_Container_StationType_free;
asn_struct_print_f ITS_Container_StationType_print;
asn_constr_check_f ITS_Container_StationType_constraint;
ber_type_decoder_f ITS_Container_StationType_decode_ber;
der_type_encoder_f ITS_Container_StationType_encode_der;
xer_type_decoder_f ITS_Container_StationType_decode_xer;
xer_type_encoder_f ITS_Container_StationType_encode_xer;
oer_type_decoder_f ITS_Container_StationType_decode_oer;
oer_type_encoder_f ITS_Container_StationType_encode_oer;
per_type_decoder_f ITS_Container_StationType_decode_uper;
per_type_encoder_f ITS_Container_StationType_encode_uper;
per_type_decoder_f ITS_Container_StationType_decode_aper;
per_type_encoder_f ITS_Container_StationType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ITS_Container_StationType_H_ */
#include <asn_internal.h>
