/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "IVI"
 * 	found in "/tmp/gen_env/build/asn1/ISO19321IVIv2.asn"
 * 	`asn1c -D /tmp/gen_env/vcits/ivim -R -no-gen-example -fcompound-names -fno-include-deps -pdu=IVIM`
 */

#ifndef	_IviStructure_H_
#define	_IviStructure_H_


#include <asn_application.h>

/* Including external dependencies */
#include "IviManagementContainer.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct IviContainers;

/* IviStructure */
typedef struct IviStructure {
	IviManagementContainer_t	 mandatory;
	struct IviContainers	*optional;	/* OPTIONAL */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} IviStructure_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_IviStructure;
extern asn_SEQUENCE_specifics_t asn_SPC_IviStructure_specs_1;
extern asn_TYPE_member_t asn_MBR_IviStructure_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _IviStructure_H_ */
#include <asn_internal.h>
