/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "EfcDsrcApplication"
 * 	found in "/tmp/gen_env/../vehicle_captain_its_asn1_specifications/etsi/is_ts103301/iso-patched/ISO14906(2018)EfcDsrcApplicationv6-patched.asn"
 * 	`asn1c -D /tmp/gen_env/vcits/ivim -R -no-gen-example -fcompound-names -fno-include-deps -pdu=IVIM`
 */

#ifndef	_VehicleClass_H_
#define	_VehicleClass_H_


#include <asn_application.h>

/* Including external dependencies */
#include "Int1.h"

#ifdef __cplusplus
extern "C" {
#endif

/* VehicleClass */
typedef Int1_t	 VehicleClass_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_VehicleClass;
asn_struct_free_f VehicleClass_free;
asn_struct_print_f VehicleClass_print;
asn_constr_check_f VehicleClass_constraint;
ber_type_decoder_f VehicleClass_decode_ber;
der_type_encoder_f VehicleClass_encode_der;
xer_type_decoder_f VehicleClass_decode_xer;
xer_type_encoder_f VehicleClass_encode_xer;
oer_type_decoder_f VehicleClass_decode_oer;
oer_type_encoder_f VehicleClass_encode_oer;
per_type_decoder_f VehicleClass_decode_uper;
per_type_encoder_f VehicleClass_encode_uper;
per_type_decoder_f VehicleClass_decode_aper;
per_type_encoder_f VehicleClass_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _VehicleClass_H_ */
#include <asn_internal.h>
