/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "CPM-PDU-Descriptions"
 * 	found in "/tmp/gen_env/../vehicle_captain_its_asn1_specifications/experimental/CPM-PDU-Descriptions.asn"
 * 	`asn1c -D /tmp/gen_env/vcits/cpm -R -no-gen-example -fcompound-names -fno-include-deps -pdu=CPM`
 */

#ifndef	_SensorType_H_
#define	_SensorType_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum SensorType {
	SensorType_undefined	= 0,
	SensorType_radar	= 1,
	SensorType_lidar	= 2,
	SensorType_monovideo	= 3,
	SensorType_stereovision	= 4,
	SensorType_nightvision	= 5,
	SensorType_ultrasonic	= 6,
	SensorType_pmd	= 7,
	SensorType_fusion	= 8,
	SensorType_inductionloop	= 9,
	SensorType_sphericalCamera	= 10,
	SensorType_itssaggregation	= 11
} e_SensorType;

/* SensorType */
typedef long	 SensorType_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_SensorType_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_SensorType;
asn_struct_free_f SensorType_free;
asn_struct_print_f SensorType_print;
asn_constr_check_f SensorType_constraint;
ber_type_decoder_f SensorType_decode_ber;
der_type_encoder_f SensorType_encode_der;
xer_type_decoder_f SensorType_decode_xer;
xer_type_encoder_f SensorType_encode_xer;
oer_type_decoder_f SensorType_decode_oer;
oer_type_encoder_f SensorType_encode_oer;
per_type_decoder_f SensorType_decode_uper;
per_type_encoder_f SensorType_encode_uper;
per_type_decoder_f SensorType_decode_aper;
per_type_encoder_f SensorType_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _SensorType_H_ */
#include <asn_internal.h>
