/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

#ifndef _ASN_CONSTANT_H
#define _ASN_CONSTANT_H

#ifdef __cplusplus
extern "C" {
#endif

#define min_val_ItsAID (0)
#define max_val_ItsAID (2113663)
#define min_val_SSPLen (0)
#define max_val_SSPLen (255)


#ifdef __cplusplus
}
#endif

#endif /* _ASN_CONSTANT_H */
