/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VC-Container"
 * 	found in "/tmp/gen_env/../vehicle_captain_its_asn1_specifications/custom/VC-Container-PDU-Descriptions.asn"
 * 	`asn1c -D /tmp/gen_env/vcits/vccontainer -R -no-gen-example -fcompound-names -fno-include-deps -pdu=RawRxMessage -pdu=RawTxMessage`
 */

#ifndef	_ItsAID_H_
#define	_ItsAID_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>

#ifdef __cplusplus
extern "C" {
#endif

/* ItsAID */
typedef long	 ItsAID_t;

/* Implementation */
extern asn_per_constraints_t asn_PER_type_ItsAID_constr_1;
extern asn_TYPE_descriptor_t asn_DEF_ItsAID;
asn_struct_free_f ItsAID_free;
asn_struct_print_f ItsAID_print;
asn_constr_check_f ItsAID_constraint;
ber_type_decoder_f ItsAID_decode_ber;
der_type_encoder_f ItsAID_encode_der;
xer_type_decoder_f ItsAID_decode_xer;
xer_type_encoder_f ItsAID_encode_xer;
oer_type_decoder_f ItsAID_decode_oer;
oer_type_encoder_f ItsAID_encode_oer;
per_type_decoder_f ItsAID_decode_uper;
per_type_encoder_f ItsAID_encode_uper;
per_type_decoder_f ItsAID_decode_aper;
per_type_encoder_f ItsAID_encode_aper;

#ifdef __cplusplus
}
#endif

#endif	/* _ItsAID_H_ */
#include <asn_internal.h>
