/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VC-Container"
 * 	found in "/tmp/gen_env/../vehicle_captain_its_asn1_specifications/custom/VC-Container-PDU-Descriptions.asn"
 * 	`asn1c -D /tmp/gen_env/vcits/vccontainer -R -no-gen-example -fcompound-names -fno-include-deps -pdu=RawRxMessage -pdu=RawTxMessage`
 */

#ifndef	_LocalInfo_H_
#define	_LocalInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include "TimeVal.h"
#include "PositionInfo.h"
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* LocalInfo */
typedef struct LocalInfo {
	TimeVal_t	 timestamp;
	PositionInfo_t	 positionInfo;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} LocalInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_LocalInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_LocalInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_LocalInfo_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _LocalInfo_H_ */
#include <asn_internal.h>
