/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VC-Container"
 * 	found in "/tmp/gen_env/../vehicle_captain_its_asn1_specifications/custom/VC-Container-PDU-Descriptions.asn"
 * 	`asn1c -D /tmp/gen_env/vcits/vccontainer -R -no-gen-example -fcompound-names -fno-include-deps -pdu=RawRxMessage -pdu=RawTxMessage`
 */

#ifndef	_TxInfo_H_
#define	_TxInfo_H_


#include <asn_application.h>

/* Including external dependencies */
#include <NativeInteger.h>
#include "TxSecurity.h"
#include "PositionInfo.h"
#include "AreaTypeInfo.h"
#include <BOOLEAN.h>
#include <constr_SEQUENCE.h>

#ifdef __cplusplus
extern "C" {
#endif

/* TxInfo */
typedef struct TxInfo {
	long	 destPort;
	long	 dataRate;
	long	 txPower;
	long	 trafficClassID;
	TxSecurity_t	 security;
	PositionInfo_t	 positionInfo;
	AreaTypeInfo_t	 areaTypeInfo;
	BOOLEAN_t	 destPortPresent;
	BOOLEAN_t	 dataRatePresent;
	BOOLEAN_t	 txPowerPresent;
	BOOLEAN_t	 trafficClassIDPresent;
	BOOLEAN_t	 securityPresent;
	BOOLEAN_t	 positionInfoPresent;
	BOOLEAN_t	 areaTypeInfoPresent;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TxInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TxInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_TxInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_TxInfo_1[14];

#ifdef __cplusplus
}
#endif

#endif	/* _TxInfo_H_ */
#include <asn_internal.h>
