/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VC-Container"
 * 	found in "/tmp/gen_env/../vehicle_captain_its_asn1_specifications/custom/VC-Container-PDU-Descriptions.asn"
 * 	`asn1c -D /tmp/gen_env/vcits/vccontainer -R -no-gen-example -fcompound-names -fno-include-deps -pdu=RawRxMessage -pdu=RawTxMessage`
 */

#include "RawRxMessage.h"

#include "LocalInfo.h"
static int
memb_payloadSize_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= 0 && value <= 1500)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_payloadString_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	const OCTET_STRING_t *st = (const OCTET_STRING_t *)sptr;
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	size = st->size;
	
	if((size >= 1 && size <= 1500)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_payloadSize_constr_4 CC_NOTUSED = {
	{ 2, 1 }	/* (0..1500) */,
	-1};
static asn_per_constraints_t asn_PER_memb_payloadSize_constr_4 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 11,  11,  0,  1500 }	/* (0..1500) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_payloadString_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..1500)) */};
static asn_per_constraints_t asn_PER_memb_payloadString_constr_5 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 11,  11,  1,  1500 }	/* (SIZE(1..1500)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_RawRxMessage_1[] = {
	{ ATF_POINTER, 1, offsetof(struct RawRxMessage, localInfo),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LocalInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"localInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RawRxMessage, rxInfo),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RxInfo,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"rxInfo"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RawRxMessage, payloadSize),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_payloadSize_constr_4, &asn_PER_memb_payloadSize_constr_4,  memb_payloadSize_constraint_1 },
		0, 0, /* No default value */
		"payloadSize"
		},
	{ ATF_POINTER, 1, offsetof(struct RawRxMessage, payloadString),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_OCTET_STRING,
		0,
		{ &asn_OER_memb_payloadString_constr_5, &asn_PER_memb_payloadString_constr_5,  memb_payloadString_constraint_1 },
		0, 0, /* No default value */
		"payloadString"
		},
};
static const int asn_MAP_RawRxMessage_oms_1[] = { 0, 3 };
static const ber_tlv_tag_t asn_DEF_RawRxMessage_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RawRxMessage_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* localInfo */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* rxInfo */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* payloadSize */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* payloadString */
};
static asn_SEQUENCE_specifics_t asn_SPC_RawRxMessage_specs_1 = {
	sizeof(struct RawRxMessage),
	offsetof(struct RawRxMessage, _asn_ctx),
	asn_MAP_RawRxMessage_tag2el_1,
	4,	/* Count of tags in the map */
	asn_MAP_RawRxMessage_oms_1,	/* Optional members */
	2, 0,	/* Root/Additions */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RawRxMessage = {
	"RawRxMessage",
	"RawRxMessage",
	&asn_OP_SEQUENCE,
	asn_DEF_RawRxMessage_tags_1,
	sizeof(asn_DEF_RawRxMessage_tags_1)
		/sizeof(asn_DEF_RawRxMessage_tags_1[0]), /* 1 */
	asn_DEF_RawRxMessage_tags_1,	/* Same as above */
	sizeof(asn_DEF_RawRxMessage_tags_1)
		/sizeof(asn_DEF_RawRxMessage_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RawRxMessage_1,
	4,	/* Elements count */
	&asn_SPC_RawRxMessage_specs_1	/* Additional specs */
};

