/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "VC-Container"
 * 	found in "/tmp/gen_env/../vehicle_captain_its_asn1_specifications/custom/VC-Container-PDU-Descriptions.asn"
 * 	`asn1c -D /tmp/gen_env/vcits/vccontainer -R -no-gen-example -fcompound-names -fno-include-deps -pdu=RawRxMessage -pdu=RawTxMessage`
 */

#include "TimeVal.h"

static int
memb_sec_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= (-2147483647L - 1) && value <= 2147483647)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_usec_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	long value;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	value = *(const long *)sptr;
	
	if((value >= (-2147483647L - 1) && value <= 2147483647)) {
		/* Constraint check succeeded */
		return 0;
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_memb_sec_constr_2 CC_NOTUSED = {
	{ 4, 0 }	/* (-2147483648..2147483647) */,
	-1};
static asn_per_constraints_t asn_PER_memb_sec_constr_2 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1, (-2147483647L - 1),  2147483647 }	/* (-2147483648..2147483647) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_usec_constr_3 CC_NOTUSED = {
	{ 4, 0 }	/* (-2147483648..2147483647) */,
	-1};
static asn_per_constraints_t asn_PER_memb_usec_constr_3 CC_NOTUSED = {
	{ APC_CONSTRAINED,	 32, -1, (-2147483647L - 1),  2147483647 }	/* (-2147483648..2147483647) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
asn_TYPE_member_t asn_MBR_TimeVal_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct TimeVal, sec),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_sec_constr_2, &asn_PER_memb_sec_constr_2,  memb_sec_constraint_1 },
		0, 0, /* No default value */
		"sec"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct TimeVal, usec),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_NativeInteger,
		0,
		{ &asn_OER_memb_usec_constr_3, &asn_PER_memb_usec_constr_3,  memb_usec_constraint_1 },
		0, 0, /* No default value */
		"usec"
		},
};
static const ber_tlv_tag_t asn_DEF_TimeVal_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_TimeVal_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* sec */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* usec */
};
asn_SEQUENCE_specifics_t asn_SPC_TimeVal_specs_1 = {
	sizeof(struct TimeVal),
	offsetof(struct TimeVal, _asn_ctx),
	asn_MAP_TimeVal_tag2el_1,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	-1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_TimeVal = {
	"TimeVal",
	"TimeVal",
	&asn_OP_SEQUENCE,
	asn_DEF_TimeVal_tags_1,
	sizeof(asn_DEF_TimeVal_tags_1)
		/sizeof(asn_DEF_TimeVal_tags_1[0]), /* 1 */
	asn_DEF_TimeVal_tags_1,	/* Same as above */
	sizeof(asn_DEF_TimeVal_tags_1)
		/sizeof(asn_DEF_TimeVal_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_TimeVal_1,
	2,	/* Elements count */
	&asn_SPC_TimeVal_specs_1	/* Additional specs */
};

